# Generated by Django 3.2.16 on 2024-12-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('performer', models.CharField(max_length=256, verbose_name='Исполнитель')),
                ('album', models.CharField(max_length=256, verbose_name='Альбом')),
                ('genre', models.CharField(max_length=256, verbose_name='Жанр')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('duration', models.CharField(max_length=10, verbose_name='Продолжительность')),
            ],
            options={
                'verbose_name': 'композиция',
                'verbose_name_plural': 'Композиции',
            },
        ),
    ]
