# Generated by Django 3.2.16 on 2024-12-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20241215_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.performer', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='music',
            name='performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.performer', verbose_name='Исполнитель'),
        ),
    ]
