# Generated by Django 3.2.16 on 2024-12-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20241216_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='image',
        ),
    ]
