# Generated by Django 3.2.16 on 2024-12-16 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_favoritealbum_favoritemusic_favoriteperformer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteperformer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoriteperformer',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='favoriteperformer',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='favoritemusic',
            options={'verbose_name': 'Избранная музыка', 'verbose_name_plural': 'Избранная музыка'},
        ),
        migrations.AlterField(
            model_name='favoritemusic',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.music', verbose_name='Музыка'),
        ),
        migrations.AlterField(
            model_name='favoritemusic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='FavoriteAlbum',
        ),
        migrations.DeleteModel(
            name='FavoritePerformer',
        ),
    ]
